title: "Robot psychologist's blog"
author:
  name: "Busra Tugce Gurbuz"
  email: "your-email@domain.com"

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Welcome to Robot Psychologist's Blog — a blog where I unpack the inner workings of intelligent systems, one curious question at a time. 
  I'm a PhD student in AI with a BSc in neuroscience and psychology, and this is my space to explore the ideas, research papers, experiments, and code that excite me most — from cognitive inspirations to quirky failures, from memory in agents to vision models 
  and beyond. If you're into how intelligent systems (human or artificial) learn, adapt, and act, you'll feel right at home.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
# remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  skin: classic

  # If you want to link only specific pages in the site-navigation, use this and list
  # the `path` property (as represented via Liquid) of the pages in the order they should
  # be rendered.
  nav_pages:
    - about.md

  # Set to `true` to show excerpts on the homepage.
  # show_excerpts: false

  # Minima date format.
  # date_format: "%b-%d-%Y"

  # Social Media Links
  # Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  # social_links:
  #   - title: Minima Theme repository at GitHub
  #     icon: github
  #     url: "https://github.com/jekyll/minima"
  #   - title: Jekyll at X (formerly Twitter)
  #     icon: x-twitter
  #     url: "https://x.com/jekyllrb"
